# Generated by Django 5.0.6 on 2024-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.CharField(blank=True, max_length=10240),
        ),
    ]
