# Generated by Django 5.0.6 on 2024-08-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_submission_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='front_page',
            field=models.TextField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.CharField(blank=True, default='None', max_length=10240),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A1', ''), ('A2', ''), ('A3', ''), ('A4', '')], max_length=256)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz')),
            ],
        ),
    ]
