# Generated by Django 5.0.6 on 2024-08-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_submission_graded_alter_submission_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='frontPage',
            new_name='front_page',
        ),
    ]
