# Generated by Django 5.0.6 on 2024-08-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_course_front_page_alter_submission_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='body',
            field=models.TextField(max_length=10240),
        ),
    ]
